/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Calculadora */

#ifndef _Included_Calculadora
#define _Included_Calculadora
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Calculadora
 * Method:    SumaC
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_Calculadora_SumaC
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     Calculadora
 * Method:    RestaC
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_Calculadora_RestaC
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     Calculadora
 * Method:    MultiplicacionC
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_Calculadora_MultiplicacionC
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     Calculadora
 * Method:    DivisionC
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_Calculadora_DivisionC
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
